[buildPlans.Iosvmata]
family = "Iosvmata"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
webfontFormats = ["ttf"]
hintParams = ["-a", "qqq"]

[buildPlans.Iosvmata.variants]
inherits = "ss08"

[buildPlans.Iosvmata.variants.design]
capital-j = "serifed"
f = "flat-hook-serifed"
l = "serifed"
zero = "slashed"
three = "flat-top-serifless"
paren = "normal"
brace = "curly-flat-boundary"
ampersand = "closed"
percent = "rings-continuous-slash"
caret = "low"

[buildPlans.Iosvmata.ligations]
inherits = "default-calt"
disables = []
enables = []

[buildPlans.Iosvmata.weights.Regular]
shape = 425
menu = 400
css = 400

[buildPlans.Iosvmata.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Iosvmata.weights.Bold]
shape = 800
menu = 700
css = 700

[buildPlans.Iosvmata.weights.Black]
shape = 900
menu = 900
css = 900

[buildPlans.Iosvmata.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Iosvmata.slopes.Oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"

[buildPlans.Iosvmata.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.Iosvmata.widths.normal]
shape = 550
menu = 5
css = "normal"

[buildPlans.Iosvmata.metricOverride]
leading = 1100
xHeight = 550
