[buildPlans.Iosvmata]
family = "Iosvmata"
spacing = "fixed"
serifs = "sans"
noCvSs= true
exportGlyphNames = false

hintParams = ["-a", "qqq"]

[buildPlans.Iosvmata.variants]
inherits = "ss08"

[buildPlans.Iosvmata.widths.normal]
shape = 550
menu  = 5
css   = "normal"

[buildPlans.Iosvmata.metricOverride]
leading = 1100
xHeight = 550

[buildPlans.Iosvmata.variants.design]
capital-j = "serifed"
f = "flat-hook-serifed"
l = "serifed"
zero = "slashed"
three = "flat-top-serifless"
paren = "normal"
brace = "curly-flat-boundary"
ampersand = "closed"
percent = "rings-continuous-slash"
caret = "low"

[buildPlans.Iosvmata.weights.regular]
shape = 425
menu = 400
css = 400

[buildPlans.Iosvmata.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.Iosvmata.weights.bold]
shape = 800
menu = 700
css = 700

[buildPlans.Iosvmata.weights.black]
shape = 900
menu = 900
css = 900

[buildPlans.Iosvmata.slopes]
Upright = "default.Upright"
Italic = "default.Italic"
